--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11 (fcae950)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attempt_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_answers (
    id character varying(50) NOT NULL,
    is_correct boolean NOT NULL,
    question_id character varying(50) NOT NULL,
    selected_option integer,
    attempt_id character varying(50) NOT NULL
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id character varying(50) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credentials (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    user_id bigint
);


--
-- Name: credentials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credentials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credentials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_attempts (
    id character varying(50) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    score double precision NOT NULL,
    time_spent integer NOT NULL,
    total_correct integer NOT NULL,
    user_id character varying(50) NOT NULL,
    exam_id character varying(50) NOT NULL
);


--
-- Name: exam_ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_ratings (
    id character varying(50) NOT NULL,
    exam_id character varying(50) NOT NULL,
    user_id character varying(50) NOT NULL,
    rating integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT check_exam_rating_range CHECK (((rating >= 1) AND (rating <= 5)))
);


--
-- Name: exams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exams (
    id character varying(50) NOT NULL,
    title jsonb NOT NULL,
    category_id character varying(50) NOT NULL,
    image text,
    duration integer NOT NULL,
    question_count integer NOT NULL,
    description jsonb,
    participants integer DEFAULT 0,
    rating numeric(3,2) DEFAULT 0.0,
    rating_count integer DEFAULT 0,
    CONSTRAINT check_rating_range CHECK (((rating >= (0)::numeric) AND (rating <= (5)::numeric)))
);


--
-- Name: knowledge_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_chunks (
    id bigint NOT NULL,
    source_type character varying(32) NOT NULL,
    source_id character varying(128) NOT NULL,
    topic_id character varying(64),
    topic_name character varying(255),
    lang character varying(8) DEFAULT 'en'::character varying NOT NULL,
    chunk_index integer NOT NULL,
    chunk_text text NOT NULL,
    token_count integer,
    embedding public.vector(3072) NOT NULL,
    metadata text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    chunk_strategy character varying(32) DEFAULT 'WORD_WINDOW'::character varying NOT NULL
);


--
-- Name: knowledge_chunks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.knowledge_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: knowledge_chunks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.knowledge_chunks_id_seq OWNED BY public.knowledge_chunks.id;


--
-- Name: learning_materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_materials (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    category character varying(50),
    type character varying(50),
    file_url character varying(500),
    image_url character varying(500),
    description text,
    title character varying(255) NOT NULL
);


--
-- Name: learning_materials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.questions (
    id character varying(50) NOT NULL,
    exam_id character varying(50) NOT NULL,
    text text NOT NULL,
    options jsonb NOT NULL,
    correct_answer integer NOT NULL,
    question_order integer,
    topic_id character varying(50)
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(36) NOT NULL,
    credential_id bigint NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topic_edges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topic_edges (
    id character varying(50) NOT NULL,
    from_topic_id character varying(50) NOT NULL,
    to_topic_id character varying(50) NOT NULL,
    relation_type character varying(50) NOT NULL
);


--
-- Name: topics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topics (
    id character varying(50) NOT NULL,
    category_name character varying(100),
    exam_type character varying(50),
    level integer,
    name character varying(255) NOT NULL
);


--
-- Name: user_topic_mastery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_topic_mastery (
    id character varying(50) NOT NULL,
    user_id character varying(50) NOT NULL,
    topic_id character varying(50) NOT NULL,
    mastery_score double precision DEFAULT 0 NOT NULL,
    error_rate double precision DEFAULT 0 NOT NULL,
    total_attempts integer DEFAULT 0 NOT NULL,
    correct_answers integer DEFAULT 0 NOT NULL,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    current_status character varying(255),
    name character varying(255),
    phone_number character varying(255),
    avatar_url character varying(255),
    created_at timestamp with time zone,
    email character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_chunks id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_chunks ALTER COLUMN id SET DEFAULT nextval('public.knowledge_chunks_id_seq'::regclass);


--
-- Name: attempt_answers attempt_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_answers
    ADD CONSTRAINT attempt_answers_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pk PRIMARY KEY (id);


--
-- Name: credentials credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credentials
    ADD CONSTRAINT credentials_pkey PRIMARY KEY (id);


--
-- Name: exam_attempts exam_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempts
    ADD CONSTRAINT exam_attempts_pkey PRIMARY KEY (id);


--
-- Name: exam_ratings exam_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_ratings
    ADD CONSTRAINT exam_ratings_pkey PRIMARY KEY (id);


--
-- Name: exams exams_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pk PRIMARY KEY (id);


--
-- Name: knowledge_chunks knowledge_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_pkey PRIMARY KEY (id);


--
-- Name: learning_materials learning_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_materials
    ADD CONSTRAINT learning_materials_pkey PRIMARY KEY (id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);


--
-- Name: topic_edges topic_edges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_edges
    ADD CONSTRAINT topic_edges_pkey PRIMARY KEY (id);


--
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);


--
-- Name: topics uk_topic_exam_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT uk_topic_exam_name UNIQUE (exam_type, name);


--
-- Name: user_topic_mastery uk_user_topic; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_topic_mastery
    ADD CONSTRAINT uk_user_topic UNIQUE (user_id, topic_id);


--
-- Name: knowledge_chunks uq_chunk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT uq_chunk UNIQUE (source_type, source_id, chunk_index, chunk_strategy);


--
-- Name: exam_ratings uq_exam_ratings_exam_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_ratings
    ADD CONSTRAINT uq_exam_ratings_exam_user UNIQUE (exam_id, user_id);


--
-- Name: user_topic_mastery user_topic_mastery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_topic_mastery
    ADD CONSTRAINT user_topic_mastery_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_chunks_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_source ON public.knowledge_chunks USING btree (source_type, source_id);


--
-- Name: idx_chunks_strategy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_strategy ON public.knowledge_chunks USING btree (chunk_strategy);


--
-- Name: idx_chunks_topic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_topic ON public.knowledge_chunks USING btree (topic_id);


--
-- Name: idx_topic_edges_from; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_topic_edges_from ON public.topic_edges USING btree (from_topic_id);


--
-- Name: idx_topic_edges_relation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_topic_edges_relation ON public.topic_edges USING btree (relation_type);


--
-- Name: idx_topic_edges_to; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_topic_edges_to ON public.topic_edges USING btree (to_topic_id);


--
-- Name: idx_user_topic_mastery_mastery_score; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_topic_mastery_mastery_score ON public.user_topic_mastery USING btree (mastery_score DESC);


--
-- Name: idx_user_topic_mastery_topic_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_topic_mastery_topic_id ON public.user_topic_mastery USING btree (topic_id);


--
-- Name: idx_user_topic_mastery_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_topic_mastery_user_id ON public.user_topic_mastery USING btree (user_id);


--
-- Name: exams exams_categories_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_categories_id_fk FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: exam_attempts fk5tomiiinihc09ywy0wh15pi2cs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempts
    ADD CONSTRAINT fk5tomiiinihc09ywy0wh15pi2cs FOREIGN KEY (exam_id) REFERENCES public.exams(id);


--
-- Name: exam_ratings fk_exam_ratings_exam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_ratings
    ADD CONSTRAINT fk_exam_ratings_exam FOREIGN KEY (exam_id) REFERENCES public.exams(id);


--
-- Name: refresh_tokens fk_refresh_tokens_credentials; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_credentials FOREIGN KEY (credential_id) REFERENCES public.credentials(id);


--
-- Name: topic_edges fk_topic_edges_from; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_edges
    ADD CONSTRAINT fk_topic_edges_from FOREIGN KEY (from_topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;


--
-- Name: topic_edges fk_topic_edges_to; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_edges
    ADD CONSTRAINT fk_topic_edges_to FOREIGN KEY (to_topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;


--
-- Name: user_topic_mastery fk_user_topic_mastery_topic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_topic_mastery
    ADD CONSTRAINT fk_user_topic_mastery_topic FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;


--
-- Name: questions fkdb5p6ukb0v76he4pq87cbymhg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkdb5p6ukb0v76he4pq87cbymhg FOREIGN KEY (topic_id) REFERENCES public.topics(id);


--
-- Name: attempt_answers fko5l8lds50jeasb0ko4m15bsti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_answers
    ADD CONSTRAINT fko5l8lds50jeasb0ko4m15bsti FOREIGN KEY (attempt_id) REFERENCES public.exam_attempts(id);


--
-- Name: questions questions_exam_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id);


--
-- PostgreSQL database dump complete
--


